# Generated by Django 4.1.7 on 2023-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaults/animal_default.png', upload_to='animals/')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Nome Científico')),
                ('status', models.IntegerField(choices=[(0, 'Extinto'), (1, 'Ameaçado de Extinção')], verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
