# Generated by Django 4.2.7 on 2023-12-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='instagram',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizations',
            name='instagram_link',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
    ]
